# Generated by Django 5.0.4 on 2024-04-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Место где стоит мужик ', 'verbose_name_plural': 'Место где стоят мужики '},
        ),
    ]
